name: sixam_mart_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  bluetooth_thermal_printer:
    path: C:/Users/moham/Downloads/BluetoothThermalPrinter-master/BluetoothThermalPrinter-master
  cached_network_image: ^3.3.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  esc_pos_utils: ^1.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_callkit_incoming:
    git:
      url: https://github.com/hiennguyen92/flutter_callkit_incoming
      ref: 1.0.2+2
  flutter_html: ^3.0.0-alpha.6
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pos_printer_platform: 1.0.12
  flutter_star_prnt:
    path: C:/Users/moham/Downloads/flutter_star_prnt-master/flutter_star_prnt-master
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.3.7
  geolocator: ^9.0.2
  get: ^4.6.1
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.3
  http_parser: ^4.0.2
  image: ^3.0.2
  flutter_image_compress: ^2.4.0
  image_picker: ^0.8.0+4
  intl: ^0.19.0
  path: ^1.8.1
  path_provider: ^2.0.2
  phone_number: ^1.0.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.2.0
  screenshot: ^2.3.0
  shared_preferences: ^2.0.6
  shimmer_animation: ^2.0.0
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
  vibration: ^1.7.6
  win32: ^3.1.3

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_copy.jpg"

dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900
