// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmp43G2pk4-CRCEph6bsljpJKzXXK7bY',
    appId: '1:187788958576:web:4bc503925f6b5834544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    // authDomain: 'qareeb-31d01.firebaseapp.com',
    // storageBucket: 'qareeb-31d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XW8Ha8hxRG1SJONcJ7wzY5pQJpkR-Os',
    appId: '1:187788958576:android:d320a73432e8549d544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    storageBucket: 'qareeb-31d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpdws6P9SOF_ZWYvDYW_gblus2DKoXCc',
    appId: '1:187788958576:ios:92a99f7397e07ea2544db5',
    messagingSenderId: '187788958576',
    projectId: 'qareeb-31d01',
    storageBucket: 'qareeb-31d01.appspot.com',
    androidClientId: '187788958576-3cdifnmkruffqngbmld5ittmpb1t6b70.apps.googleusercontent.com',
    iosClientId: '187788958576-lfejj3jnlcb6kqqutj9fee5b08q7hj4p.apps.googleusercontent.com',
    iosBundleId: 'semicolon.qareb.tager',
  );
}
